# wrangler.toml (for auth-worker)
# Configuration for the dedicated Authentication Server Worker.

name = "auth-worker" # Unique name for the authentication worker
main = "src/index.ts" # Entry point for the worker code
compatibility_date = "2024-04-05" # Use a recent compatibility date

# Account ID - Replace with your actual Cloudflare account ID
# You can find this in your Cloudflare dashboard URL or settings.
# account_id = "<YOUR_CLOUDFLARE_ACCOUNT_ID>" # !!! IMPORTANT: REPLACE THIS !!!

# KV Namespace Binding for OAuth data (tokens, codes, state)
# Create this namespace in your Cloudflare dashboard.
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "fb732683ae9a42349e0d0a7e5fc4cc44" # !!! IMPORTANT: REPLACE THIS with the ID from your dashboard !!!
preview_id = "fb732683ae9a42349e0d0a7e5fc4cc44" # !!! Optional but recommended for wrangler dev: REPLACE THIS !!!

# Secrets - Set these using 'wrangler secret put <NAME>' in the auth-worker directory
# Use secrets for production and sensitive values.
# wrangler secret put HANKO_API_URL
# wrangler secret put OAUTH_SIGNING_KEY # Private key for signing JWT Access Tokens (if not auto-generated by library)
# wrangler secret put JWT_SECRET # Optional: For internal use if needed

# Variables - Non-secret configuration or local overrides
[vars]
CLIENT_APP_URL = "http://localhost:3000" # Default/Placeholder Client App URL (Override in [env.dev.vars] or use secret for prod)
MCP_WORKER_URL = "http://localhost:8789" 
HANKO_API_URL = "https://77d5a9fe-53c9-4e73-9af7-f4defbc80295.hanko.io" # Placeholder Hanko API URL (Use secret for prod)
# OAUTH_PUBLIC_KEY_JWK: Public key (in JWK format) corresponding to OAUTH_SIGNING_KEY for the /jwks.json endpoint
# This can be set here if not sensitive, otherwise consider storing securely or generating dynamically.
# OAUTH_PUBLIC_KEY_JWK = '{"kty": "...", "kid": "...", ...}' # Example JWK format
OAUTH_SIGNING_KEY = "3e7960e6dab4174b3d4a3393e253316d753935c35872f54d292b146159904950"
OAUTH_ISSUER_URL = "http://localhost:8788"

# Development server settings
[dev]
port = 8788 # Use a different port from the main app and potential resource server worker
local_protocol = "http"

# Development Environment Variables - Overrides [vars] during `wrangler dev`
[env.dev.vars]
CLIENT_APP_URL = "http://localhost:3000" # Explicitly set for local development
MCP_WORKER_URL = "http://localhost:8789" # URL where mcp-worker is running
# HANKO_API_URL = "YOUR_DEV_HANKO_URL" # Can override Hanko URL for dev here if needed

# Build configuration (optional, customize if needed)
# [build]

# Enable workers.dev route for easy deployment/testing
workers_dev = true
